- platform: min_max
  unique_id: 'serverkast_totaal_vermogen'
  name: 'Serverkast totaal vermogen'
  type: sum
  round_digits: 0
  entity_ids:
    - sensor.serverkast_boven_power
    - sensor.serverkast_onder_power
- platform: min_max
  unique_id: 'serverkast_totale_stroomsterkte'
  name: 'Serverkast totale stroomsterkte'
  type: sum
  round_digits: 2
  entity_ids:
    - sensor.serverkast_boven_current
    - sensor.serverkast_onder_current

