- id: '1729712269362'
  alias: Keuken nacht verlichting aan
  description: Schakel de verlichting in de keuken in als er beweging is.
  triggers:
    - trigger: state
        entity_id:
        - binary_sensor.beweging_keuken_rechts_occupancy
        - binary_sensor.beweging_keuken_links_occupancy
        to: 'on'
  conditions:
    - condition: and
        conditions:
          - condition: state
          entity_id: binary_sensor.beweging_keuken_rechts_occupancy
          state: 'on'
          - condition: state
          entity_id: binary_sensor.beweging_keuken_links_occupancy
          state: 'on'
          - condition: state
          entity_id: input_select.licht_keuken
          state: uit
          - condition: state
          entity_id: sun.sun
          state: below_horizon
  actions:
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.nacht_licht
  mode: single
- id: '1729712578863'
  alias: Keuken geen beweging uit
  description: Schakel de nacht verlichting uit als er geen beweging meer is.
  triggers:
    - trigger: state
      entity_id:
      - binary_sensor.beweging_keuken_rechts_occupancy
      - binary_sensor.beweging_keuken_links_occupancy
      to: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  conditions:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.beweging_keuken_rechts_occupancy
          state: 'off'
          for:
            hours: 0
            minutes: 2
            seconds: 0
        - condition: state
          entity_id: binary_sensor.beweging_keuken_links_occupancy
          state: 'off'
          for:
            hours: 0
            minutes: 2
            seconds: 0
        - condition: state
          entity_id: input_select.licht_keuken
          state: nacht
  actions:
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.licht_uit
  mode: single
- id: '1729714365586'
  alias: Trap nacht verlichting aan
  description: Schakel de verlichting van de trap in als er beweging is.
  triggers:
    - trigger: state
      entity_id:
      - binary_sensor.beweging_hal_trap_occupancy
      - binary_sensor.beweging_trap_occupancy
      to: 'on'
  conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.licht_keuken
        state: uit
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 5
  actions:
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.nacht_licht_trap
  mode: single
- id: '1729715175589'
  alias: Licht in hal uitzetten
  description: Schakel het licht in de hal uit als er geen beweging is.
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.beweging_hal_voor_occupancy
        - binary_sensor.beweging_hal_trap_occupancy
        - binary_sensor.beweging_trap_occupancy
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  conditions:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.beweging_hal_voor_occupancy
          state: 'off'
          for:
            hours: 0
            minutes: 5
            seconds: 0
        - condition: state
          entity_id: binary_sensor.beweging_hal_trap_occupancy
          state: 'off'
          for:
            hours: 0
            minutes: 5
            seconds: 0
        - condition: state
          entity_id: binary_sensor.beweging_trap_occupancy
          state: 'off'
          for:
            hours: 0
            minutes: 5
            seconds: 0
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.schakelaar_hal_1b
  mode: single
- id: '1732869159671'
  alias: Boiler temperatuur aanpassen aan gevoelstemperatuur
  description: ''
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.de_cv_wordt_gevraagd_aan_te_slaan
      to: 'on'
  actions:
    - action: input_number.set_value
      data:
        value: '{{ max(min(40 - (states(''sensor.knmi_gevoelstemperatuur'') | float
          / 2), 50), 30) }}'
      target:
        entity_id: input_number.boiler_cv_water_temperatuur
  mode: single
- id: '1735679042960'
  alias: Vloerverwarming
  description: Zet de vloerverwarming aan als de temperatuur onder de 18 graden komt
  triggers:
    - trigger: time_pattern
      minutes: '0'
      seconds: '1'
  conditions:
    - condition: numeric_state
      entity_id: sensor.woonkamer_temperatuur
      below: 18.2
  actions:
    - action: input_datetime.set_datetime
      metadata: {}
      data:
        time: 00:15:00
      target:
        entity_id: input_datetime.cv_tijd_aan
  mode: single
- id: '1755461599930'
  alias: Test
  description: ''
  triggers:
    - domain: mqtt
      device_id: a3211e177c8cdf97037fb3448b711422
      type: action
      subtype: toggle
      trigger: device
  conditions: []
  actions:
    - device_id: c377ca141034cf30b014ea7246771d88
      domain: light
      entity_id: 446eace03fa9f6add24749593e175727
      type: flash
  mode: single
