# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - "/data"
  unit_system: metric
  packages: !include_dir_merge_named packages/

recorder:
  purge_keep_days: 62

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#scene manual: !include_dir_merge_list scenes/
#input_select: !include_dir_merge_list helpers/input_select
sensor: !include_dir_merge_list sensors

#scheduler:

pyscript:
  allow_all_imports: false
  hass_is_global: false
