- platform: min_max
  unique_id: slaapkamer1_gemiddelde_temperatuur
  name: 'Master bed room gemiddelde temperatuur'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.slaapkamer1_gemeten_temperatuur
    - sensor.sensor_slaapkamer1_temperature
- platform: filter
  unique_id: slaapkamer1_temperatuur
  name: 'Master bed room temperatuur'
  entity_id: sensor.slaapkamer1_gemiddelde_temperatuur
  filters:
    - filter: time_simple_moving_average
      window_size: "00:10"
    - filter: time_throttle
      window_size: "00:01"
