- platform: history_stats
  unique_id: CV_aan_24_uur
  name: 'Brand uren verwarming in de afgelopen 24 uur'
  entity_id: binary_sensor.centrale_verwarming_leveren
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  unique_id: CV_aan_30_dagen
  name: 'Brand uren verwarming in de afgelopen 30 dagen'
  entity_id: binary_sensor.centrale_verwarming_leveren
  state: "on"
  type: time
  end: "{{ today_at('00:00') }}"
  duration:
    days: 30
- platform: history_stats
  unique_id: CV_aan_vorige_dag
  name: 'Brand uren verwarming in vorige dag'
  entity_id: binary_sensor.centrale_verwarming_leveren
  state: "on"
  type: time
  start: "{{ (today_at('00:00') - timedelta(days=1)) }}"
  end: "{{ today_at('00:00') }}"
- platform: history_stats
  unique_id: CV_aan_vorige_maand
  name: 'Brand uren verwarming in vorige maand'
  entity_id: binary_sensor.centrale_verwarming_leveren
  state: "on"
  type: time
  start: "{{ (today_at('00:00').replace(day=1) - timedelta(days=1)).replace(day=1) }}"
  end: "{{ today_at('00:00').replace(day=1) }}"

- platform: history_stats
  unique_id: WW_aan_24_uur
  name: 'Brand uren warm water in de afgelopen 24 uur'
  entity_id: binary_sensor.warm_water_leveren
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  unique_id: WW_aan_30_dagen
  name: 'Brand uren warm water in de afgelopen 30 dagen'
  entity_id: binary_sensor.warm_water_leveren
  state: "on"
  type: time
  end: "{{ today_at('00:00') }}"
  duration:
    days: 30
- platform: history_stats
  unique_id: WW_aan_vorige_dag
  name: 'Brand uren warm water in vorige dag'
  entity_id: binary_sensor.warm_water_leveren
  state: "on"
  type: time
  start: "{{ (today_at('00:00') - timedelta(days=1)) }}"
  end: "{{ today_at('00:00') }}"
- platform: history_stats
  unique_id: WW_aan_vorige_maand
  name: 'Brand uren warm water in vorige maand'
  entity_id: binary_sensor.warm_water_leveren
  state: "on"
  type: time
  start: "{{ (today_at('00:00').replace(day=1) - timedelta(days=1)).replace(day=1) }}"
  end: "{{ today_at('00:00').replace(day=1) }}"
