- id: slaapkamer2_radiator_temperatuur_correctie
  alias: "Corrigeer de temperatuur meting van de thermostaatknop"
  description: "Corigeer de offset van de temperatuur meting van de thermostaatknop aan de hand van de gemiddelde temperatuur"
  use_blueprint:
    path: climate_offset_correction.yaml
    input:
      gemiddelde_sensor: sensor.slaapkamer_2_gemiddelde_temperatuur
      radiator_knoppen:
        - climate.radiator_slaapkamer_2
