- platform: min_max
  unique_id: slaapkamer2_gemiddelde_temperatuur
  name: 'Slaapkamer 2 gemiddelde temperatuur'
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.slaapkamer2_gemeten_temperatuur
    - sensor.sensor_slaapkamer2_temperature
- platform: filter
  unique_id: slaapkamer2_temperatuur
  name: 'Slaapkamer 2 temperatuur'
  entity_id: sensor.slaapkamer_2_gemiddelde_temperatuur
  filters:
    - filter: time_simple_moving_average
      window_size: "00:10"
    - filter: time_throttle
      window_size: "00:01"
