- id: zolder_radiator_temperatuur_correctie
  alias: "Corrigeer de temperatuur meting van de thermostaatknop"
  description: "Corigeer de offset van de temperatuur meting van de thermostaatknop aan de hand van de gemiddelde temperatuur"
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - sensor.zolder_gemiddelde_temperatuur
  action:
    - action: number.set_value
      data:
        value: "{{ ((states('sensor.zolder_gemiddelde_temperatuur') | float) - (states('sensor.zolder_gemeten_temperatuur') | float)) | round(1) }}"
      target:
        entity_id: number.radiator_zolder_local_temperature_calibration
